### ISSUE TITLE
add category->device_model_struct mapping to matpower parser

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSystems.jl#131]
in `src/parsers/pm2ps_parser.jl`, we have created some hardcoded mappings (e.g. `WIND=>RenewableCurtail()`). We need to make these configurable and more generic so that when someone passes a MATPOWER file with different generator categories, they don't have to addd a new mapping.

**Comment by jd-lara** [comment]
@daniel-thom and @jjstickel This issue is relevant to the conversation this morning. 

The files that need to be properly parsed and can be used are the following: 
Urgent 
- [ ] https://github.com/NREL/PowerSystemsTestData/tree/master/ACTIVSg2000
- [ ] https://github.com/NREL/PowerSystemsTestData/blob/master/RTS_GMLC.m

Large systems to test for bottlenecks

- [ ] https://github.com/NREL/PowerSystemsTestData/tree/master/ACTIVSg10k
- [ ] https://github.com/NREL/PowerSystemsTestData/tree/master/ACTIVSg70k

The largest file available
- [ ] https://github.com/NREL/PowerSystemsTestData/tree/master/SyntheticUSA
