### ISSUE TITLE
Missing ramp_agc is not handled in make_thermal_gen

### ISSUE THREAD

**Issue by daniel-thom** [NREL/PowerSystems.jl#148]
The function make_thermal_gen assumes that "ramp_agc" is a key in the passed dictionary.  Sometimes it is not present and so the code fails with an unhandled exception.

@claytonpbarrows @jd-lara What should ramplimits be set to in this case?

**Comment by jd-lara** [comment]
We can ignore that for now. This should be part later of the AGC service definition.

**Comment by daniel-thom** [comment]
@claytonpbarrows Based on the comment by @jd-lara I recommend moving this to a milestone that will include implementation of the AGC service definition.

**Comment by jd-lara** [comment]
I am closing this issue since it seems that the ramp_agc field is not used in matpower https://www.mail-archive.com/matpower-l@cornell.edu/msg06231.html and although the information is from 2017 there isn't anything in the current manual https://matpower.org/docs/MATPOWER-manual.pdf that contradicts the older information.
