### ISSUE TITLE
read_datetime function in dict_to_struct.jl incorrectly converts 5 minute time periods to minutes

### ISSUE THREAD

**Issue by jmaack24** [NREL/PowerSystems.jl#282]
In the function read_datetime in the file dict_to_struct.jl, the elseif clause (line 144 of the file on the master branch) meant to handle converting 5 minute time periods to the correct time of day is incorrect.  Changing to something like
```
# Subtract 1 to make period number zero based
start_per = Int(df[1,:Period] - 1)
stop_per = Int(df[end,:Period] - 1)
df[:DateTime] = collect(Dates.DateTime(df[1,:Year],df[1,:Month],df[1,:Day], floor(start_per/12), 5*(start_per - 12*floor(start_per / 12))) :
                                    Dates.Minute(5) :
                                    Dates.DateTime(df[end,:Year],df[end,:Month],df[end,:Day], floor(stop_per/12), 5*(stop_per - 12*floor(stop_per / 12)))
                                    )
```
should fix the issue.

**Comment by jd-lara** [comment]
I think this is fixed in the dev branch. @daniel-thom can you confirm please?

**Comment by daniel-thom** [comment]
I rewrote this code.  I tried to mimic the behavior of the old code, however, so it's possible that the same issue occurs.

**Comment by jmaack24** [comment]
If you have data that ends precisely on an hour, the old version tries to set the minutes to 60.  So you can easily check.

**Comment by daniel-thom** [comment]
I'm not sure that I follow.  Here is a 5-minute-resolution forecast produced with the new code.  (RTS_GMLC data, RenewableDispatch, 122_WIND_1)

```
288×1 TimeSeries.TimeArray{Float64,1,Dates.DateTime,Array{Float64,1}} 2020-01-01T00:00:00 to 2020-01-01T23:55:00
│                     │ 122_WIND_1 │
├─────────────────────┼────────────┤
│ 2020-01-01T00:00:00 │ 6.984      │
│ 2020-01-01T00:05:00 │ 7.016      │
│ 2020-01-01T00:10:00 │ 7.017      │
│ 2020-01-01T00:15:00 │ 7.021      │
│ 2020-01-01T00:20:00 │ 7.013      │
│ 2020-01-01T00:25:00 │ 7.039      │
│ 2020-01-01T00:30:00 │ 7.027      │
│ 2020-01-01T00:35:00 │ 6.966      │
│ 2020-01-01T00:40:00 │ 6.928      │
│ 2020-01-01T00:45:00 │ 6.959      │
│ 2020-01-01T00:50:00 │ 7.003      │
│ 2020-01-01T00:55:00 │ 7.0        │
│ 2020-01-01T01:00:00 │ 7.025      │
│ 2020-01-01T01:05:00 │ 6.978      │
│ 2020-01-01T01:10:00 │ 6.97       │
│ 2020-01-01T01:15:00 │ 7.004      │
│ 2020-01-01T01:20:00 │ 7.044      │
│ 2020-01-01T01:25:00 │ 7.014      │
│ 2020-01-01T01:30:00 │ 6.976      │
│ 2020-01-01T01:35:00 │ 7.017      │
│ 2020-01-01T01:40:00 │ 7.033      │
│ 2020-01-01T01:45:00 │ 6.999      │
│ 2020-01-01T01:50:00 │ 6.972      │
│ 2020-01-01T01:55:00 │ 6.968      │
│ 2020-01-01T02:00:00 │ 6.995      │
│ 2020-01-01T02:05:00 │ 7.039      │
│ 2020-01-01T02:10:00 │ 6.995      │
│ 2020-01-01T02:15:00 │ 6.989      │
│ 2020-01-01T02:20:00 │ 7.033      │
│ 2020-01-01T02:25:00 │ 7.041      │
│ 2020-01-01T02:30:00 │ 7.009      │
│ 2020-01-01T02:35:00 │ 6.944      │
│ 2020-01-01T02:40:00 │ 6.945      │
│ 2020-01-01T02:45:00 │ 7.004      │
│ 2020-01-01T02:50:00 │ 7.028      │
│ 2020-01-01T02:55:00 │ 7.017      │
│ 2020-01-01T03:00:00 │ 6.944      │
│ 2020-01-01T03:05:00 │ 6.946      │
│ 2020-01-01T03:10:00 │ 6.975      │
   ⋮
│ 2020-01-01T20:45:00 │ 5.002      │
│ 2020-01-01T20:50:00 │ 5.016      │
│ 2020-01-01T20:55:00 │ 4.993      │
│ 2020-01-01T21:00:00 │ 4.936      │
│ 2020-01-01T21:05:00 │ 4.972      │
│ 2020-01-01T21:10:00 │ 5.147      │
│ 2020-01-01T21:15:00 │ 5.341      │
│ 2020-01-01T21:20:00 │ 5.365      │
│ 2020-01-01T21:25:00 │ 5.14       │
│ 2020-01-01T21:30:00 │ 4.859      │
│ 2020-01-01T21:35:00 │ 4.617      │
│ 2020-01-01T21:40:00 │ 4.344      │
│ 2020-01-01T21:45:00 │ 4.216      │
│ 2020-01-01T21:50:00 │ 4.27       │
│ 2020-01-01T21:55:00 │ 4.465      │
│ 2020-01-01T22:00:00 │ 4.614      │
│ 2020-01-01T22:05:00 │ 4.666      │
│ 2020-01-01T22:10:00 │ 4.748      │
│ 2020-01-01T22:15:00 │ 4.902      │
│ 2020-01-01T22:20:00 │ 4.967      │
│ 2020-01-01T22:25:00 │ 4.917      │
│ 2020-01-01T22:30:00 │ 4.703      │
│ 2020-01-01T22:35:00 │ 4.458      │
│ 2020-01-01T22:40:00 │ 4.347      │
│ 2020-01-01T22:45:00 │ 4.581      │
│ 2020-01-01T22:50:00 │ 4.651      │
│ 2020-01-01T22:55:00 │ 4.444      │
│ 2020-01-01T23:00:00 │ 4.419      │
│ 2020-01-01T23:05:00 │ 4.573      │
│ 2020-01-01T23:10:00 │ 4.779      │
│ 2020-01-01T23:15:00 │ 4.965      │
│ 2020-01-01T23:20:00 │ 5.155      │
│ 2020-01-01T23:25:00 │ 5.361      │
│ 2020-01-01T23:30:00 │ 5.546      │
│ 2020-01-01T23:35:00 │ 5.668      │
│ 2020-01-01T23:40:00 │ 5.662      │
│ 2020-01-01T23:45:00 │ 5.688      │
│ 2020-01-01T23:50:00 │ 5.69       │
│ 2020-01-01T23:55:00 │ 5.756      │
```

**Comment by jmaack24** [comment]
Sorry. That was a little unclear.

I have a load time series that ends on 2020-12-31T23:00.  In the .csv file it is given in the format
`Year, Month, Day, Period`
where Period goes from 1 to 288 and period 1 corresponds to 00:00, 2 corresponds to 00:05, ..., and 288 corresponds to 23:55 (so effectively Period is the number of 5 minute intervals since the start of the day plus 1).

In the master branch, the conversion from the period number to time of day is given by
    Starting Hour = floor(df[1,:Period]/12),
    Starting Minute = Int(df[1,:Period])-1)
    Ending Hour = floor(df[end,:Period]/12)-1
    Ending Minute = 5*(Int(df[end,:Period])-(floor(df[end,:Period]/12)-1)*12) -5))
(I have reformatted the code to make it readable.) . The calculation for Starting Minute is blatantly wrong for anything other than Period=1.  For the ending minute, take my example above for 23:00.  Here Period=277.  If you do the calculations, we find that
    Ending Minute = 5*(277 - 12*(floor(277/12) - 1)) - 5 = 60
Take this and plug it into the constructor for a Dates.DateTime struct in Julia (something like `DateTime(2020,1,1,0,60)`) and you get the error
`ERROR: ArgumentError: Minute: 60 out of range (0:59)`

The Starting/Ending Hour calculation has similar issues.  If you point me to where this code ended up in the dev branch, I can check it.

**Comment by daniel-thom** [comment]
The code is now completely different.  The relevant code is here:  https://github.com/NREL/PowerSystems.jl/blob/dev/src/parsers/timeseries_formats.jl.  We've defined different timeseries formats and then use Julia's type dispatching to run the correct logic.  If your format has the Period defined in a column then you'll want to look at the functions starting on lines 115 and 200.

**Comment by jmaack24** [comment]
Perhaps you can explain something to me.  This function
```
function get_timestamp(::Type{TimeseriesFormatYMDPeriodAsColumn}, file::CSV.File,
                       row_index::Int)
    return Dates.DateTime(file.Year[row_index], file.Month[row_index], file.Day[row_index])
end
```
is not using the period at all to produce the timestamp.  Shouldn't it be using the period to compute the time of day?

If not then it seems that this assertion
```
@assert timestamp["count"] == timestamps[1]["count"]
```
in `get_unique_timestamps` (line 88) requires that the input data begin and end on a whole day.  So for instance, a time series that runs from 2020-01-01T00:00:00 to 2020-01-02T08:00:00 will be fail this assertion as would a time series from 2020-01-01T08:00:00 to 2020-01-02T23:55:00.  I don't see any reason to disallow such things.

Am I missing something?

**Comment by daniel-thom** [comment]
The code reads every timestamp in the file to identify the rows with the same YMD value.  Each group of rows with the same YMD should have a period value incrementing from 1 to n.  So, the period seems redundant.  It is simply the index into that group.

After identifying the groups of common values the code infers the timedelta between each row.  To do that it calculates the diff between each group (which should always be the same across groups) and then divides that by the number of rows in the group.  In a simple example where there are 48 rows with two YMD values each repeated 24 times, the timedelta is 1 day / 24 = 1 hour.

The next step is to calculate actual timestamps for each row.  To do that the code starts at the first YMD value, computes a DateTime for it (assumes start time of 00:00:00), and then adds the timedelta for each row.  Clayton said that I could assert that each row should be separated by the same amount of time.

You are right in that this logic assumes that the periods should be spread evenly across the entire day.  Note that for this format the lowest granularity provided is 1 day.  If more granularity is provided in the raw data then we could do better.  Is that the essence of the problem?  I think there is some placeholder code for data with actual DateTime timestamps, but haven't filled it in because we don't have any raw data like that yet.

**Comment by daniel-thom** [comment]
If you take my 48-hour example and want to shift it such that it starts at noon instead of midnight, my solution won't work.  In that case are you saying that the data would have period values that start at 13 instead of 1?  It seems like this gets very difficult to discern programmatically.  I don't get why the raw data just doesn't have timestamps.

I'm totally open to re-thinking this in order to support all desired behaviors.  It would be better to meet in person and discuss all requirements.
