### ISSUE TITLE
Fix trailing whitespace in autogenerated files 

### ISSUE THREAD

**Issue by kdheepak** [NREL/PowerSystems.jl#315]
Some files have trailing whitespace in the files that are autogenerated. They can be stripped before committing.

**Comment by daniel-thom** [comment]
There are four instances. Three of them are because a user left the whitespace in a string definition for a comment.  Those can be easily fixed.  The fourth is because of a one-line Mustache expansion of parameters (Bus call to CheckBusParams).  I could fix that by adding in extra logic to not add a space for the last parameter in the list.  A simpler fix is to put one parameter per line.

Another possible fix is re-open each generated file and strip the trailing whitespace.

A simpler fix overall is to implement a pre-commit hook that strips all trailing whitespace, and possibly other whitespace problems.

Did you have something else in mind?

**Comment by kdheepak** [comment]
I noticed in this file on this line there's a whitespace:

https://github.com/NREL/PowerSystems.jl/blob/fa8841b444c52fd2c4f6152a47ab270eea1a22d7/src/models/generated/TechThermal.jl#L7

Any approach would work.

Also, on the same line, there's a `<` that is not being rendered correctly into the template. It is being instantiated as `&lt;` which seems to be the html entity for `<`.
