### ISSUE TITLE
Broken printing 

### ISSUE THREAD

**Issue by jd-lara** [NREL/PowerSystems.jl#343]
it looks like the forecasts printing isn't showing the forecast type anymore 

```Julia
---------------------------------
Initial Time: 2020-01-01T00:00:00
---------------------------------
4×3 DataFrames.DataFrame
│ Row │ ConcreteType       │ SuperTypes                                   │ Count │
│     │ String             │ String                                       │ Int64 │
├─────┼────────────────────┼──────────────────────────────────────────────┼───────┤
│ 1   │ InterruptibleLoad} │ Forecast <: InfrastructureSystemsType <: Any │ 1     │
│ 2   │ PowerLoad}         │ Forecast <: InfrastructureSystemsType <: Any │ 3     │
│ 3   │ RenewableDispatch} │ Forecast <: InfrastructureSystemsType <: Any │ 3     │
│ 4   │ StaticReserve}     │ Forecast <: InfrastructureSystemsType <: Any │ 1     │
```

**Comment by daniel-thom** [comment]
This broke with the introduction of InfrastructureSystems.  The purpose of strip_module_names was to remove all module names from a type.  "Foo.Bar.MyType" would convert to "MyType".

In the case of "InfrastructureSystems.Deterministic{PowerSystems.HydroDispatch}" the code uses the "." before HydroDispatch as its truncation point.

- Simple fix:  call findlast instead of findfirst.  "Foo.Bar.MyType" would convert to "Bar.MyType". Should probably change the function name to "strip_module_name".
- A bit more complicated fix: write some logic to detect the last "." before any "{".

@jd-lara What do you think?

**Comment by jd-lara** [comment]
The simple fix LGTM. It will be safe to assume that anything after the `XXXSystems.` is useful information.
