### ISSUE TITLE
error in power flow result indexing. 

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/PowerSystems.jl#360]
see the `angle` value below:
```julia
julia> solve_powerflow!(c_sys14, nlsolve, method = :newton)

julia> get_component(Bus, c_sys14, "Bus 4")
Bus 4 (Bus):
   number: 4
   name: Bus 4
   bustype: PQ
   angle: 752.7238173844561
   voltage: 1.019
   voltagelimits: (min = 0.94, max = 1.06)
   basevoltage: 69.0
```

**Comment by jd-lara** [comment]
This is an issue in the `_write_pf_sol!` function and how the results are assigned. This function will break after the merge of #359 since there could be more than one generator per bus. As a result the function can't know how to assign to each generator the resulting reactive power in PV buses or the active power in the slack.

**Comment by jd-lara** [comment]
@claytonpbarrows I can't replicate this issue from the data in c_sys14.

**Comment by claytonpbarrows** [comment]
the issue only arises when you run a power flow more than once. closing
