### ISSUE TITLE
Add supplemental constructor for buses without areas and load zones

### ISSUE THREAD

**Issue by rodrigomha** [NREL/PowerSystems.jl#443]
Current constructor requires two additional nothing at the end.

**Comment by claytonpbarrows** [comment]
you can use the option that takes `basepower` and `kwargs`. So:
```julia
System(100.0, buses = [Bus(nothing)], generators = [ThermalStandard(nothing)])
```
Does that work? If there is another reason to add the you suggestion, I'm open to it, but this was the intent of the `kwargs` option.

**Comment by daniel-thom** [comment]
@claytonpbarrows I understand the request.  When we added Area and LoadZone to the Bus struct we added a requirement that the user pass both fields in the constructor.  This change broke existing code.  Since each field can be `nothing` it would make sense to make them optional.  

I'll check if we can handle this with our auto-generation code.

**Comment by daniel-thom** [comment]
@rodrigomha I think the best solution is to leave area and load_zone as required parameters for the positional-argument constructor but then allow your desired behavior with the kwarg constructor.  Here is an example.  Is this OK for you?

```
bus1 = Bus(;
           number = 1,
           name = "bus1",
           bustype = BusTypes.PV,
           angle = 1.0,
           voltage = 1.0,
           voltagelimits = (min = -1.0, max = 1.0),
           basevoltage = 1.0,
       )
```
